#ifndef CONSTANTS
#define CONSTANTS

#define endl "\n"

#define PIN_STATUS_LED 16
#define PIN_TRIG_1     23
#define PIN_TRIG_2     35
#define PIN_ECHO_1     22
#define PIN_ECHO_2     36
#define PIN_DS18       2

#define PREFIX_SENSORS       "sensor"
#define PREFIX_SPECTROMETER  "spectr"

#define SPECTROMETER_START_ANGLE 60
#define SPECTROMETER_END_ANGLE   180
#define SPECTROMETER_N_VALUES    SPECTROMETER_END_ANGLE - SPECTROMETER_START_ANGLE
#define SPECTROMETER_SAMPLING    1000
#define SPECTROMETER_REFRESH_PERIOD 600000L

#define PIN_THERMISTOR 11
#define PIN_PHOTODIODE A20
#define PIN_SERVO_SPECTROMETER 38
#define PIN_SERVO_CAMERA       37
#define PIN_SERVO_MAIZENA      32
#define INDEX_EXTERNAL  3
#define INDEX_CONVERTER 1
#define INDEX_BATTERY   2
#define INDEX_CAMERA    0

#define MILLIS_FIRST_CAM_LAUNCH   0L
#define MILLIS_FIRST_CAM_STOP     1020000L
#define MILLIS_SECOND_CAM_LAUNCH  4980000L
#define MILLIS_SECOND_CAM_STOP    6000000L
#define MILLIS_THIRD_CAM_LAUNCH   9600000L



#define MAX_SENSORS_BUFFER   20
#define SENSORS_REFRESH_RATE 2  // en hertzs


#endif
